// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/supply_chain_version.test.ts.

/** The version of the `@tssuite/supply-chain` package. */
export const supplyChainVersion = '0.1.1';
